# Generated by Django 5.2.12 on 2026-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dalbadluApp1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvertedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="original/")),
                ("converted_file", models.FileField(upload_to="converted/")),
                ("conversion_type", models.CharField(max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
